name: Build and Push image

on:
  push:
    branches: [ main ]
    paths: [ 'Dockerfile', '.github/workflows/**' ]
  workflow_dispatch:
    inputs:
      comfy_tag:
        description: 'ComfyUI tag to build (e.g. v0.3.40)'
        required: true
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
    - uses: actions/checkout@v4

    - name: Set ComfyUI version
      id: setver
      run: |
        if [[ "${{ github.event_name }}" == "release" ]]; then
          echo "version=${{ github.event.release.tag_name }}" >> "$GITHUB_OUTPUT"
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          echo "version=${{ github.event.inputs.comfy_tag }}" >> "$GITHUB_OUTPUT"
        else
          echo "version=$(grep -oP 'ARG COMFYUI_VERSION=\K.*' Dockerfile)" >> "$GITHUB_OUTPUT"
        fi

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build & push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        build-args: COMFYUI_VERSION=${{ steps.setver.outputs.version }}
        tags: |
          ghcr.io/${{ github.repository_owner }}/comfyui:${{ steps.setver.outputs.version }}
          ghcr.io/${{ github.repository_owner }}/comfyui:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
