name: Check upstream releases

on:
  schedule:
    - cron: '0 3 * * *'   # every day at 03:00 UTC

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.probe.outputs.tag }}
    steps:
      - name: Probe ComfyUI latest tag via GitHub API
        id: probe
        uses: actions/github-script@v7
        with:
          script: |
            const res = await github.rest.repos.getLatestRelease({
              owner: 'comfyanonymous',
              repo: 'ComfyUI'
            })
            const latest = res.data.tag_name
            core.info(`Upstream latest tag: ${latest}`)
            core.setOutput('tag', latest)

      - name: Check if image already exists
        id: check
        env:
          TAG: ${{ steps.probe.outputs.tag }}
        run: |
          skopeo inspect docker://ghcr.io/${{ github.repository_owner }}/comfyui:${TAG} || echo 'missing' > missing

      - name: Dispatch build if missing
        if: success() && hashFiles('missing') != ''
        uses: peter-evans/repository-dispatch@v3
        with:
          event-type: build-new-release
          client-payload: |
            {"comfy_tag": "${{ steps.probe.outputs.tag }}"}
